// Curated mapping: raw spreadsheet exercise name -> canonical resolution.
// existing:true  => must exact-match (case-insensitive) an entry already in the `exercises` catalog
// existing:false => genuinely new; `name` is the clean canonical spelling to create/use
export const MAP = {
  "1/2 kneeling landmine shoulder press": { existing: false, name: "1/2 Kneeling Landmine Shoulder Press" },
  "21s": { existing: true, name: "21s" },
  "2pt Dumbbell Row": { existing: true, name: "2pt Dumbbell Row" },
  "3 way calf raises": { existing: true, name: "3 Way Calf Raise" },
  "alternating v situp": { existing: false, name: "Alternating V Sit-Up" },
  "Anterior Raises": { existing: false, name: "Anterior Raises" },
  "Anterior Tib Raises": { existing: false, name: "Anterior Tib Raises" },
  "Anterior Tib Raises w/ Weight": { existing: false, name: "Anterior Tib Raises w/ Weight" },
  "Back Squat to Box": { existing: true, name: "Back Squat to Box" },
  "Band Assissted Jumps": { existing: false, name: "Band Assisted Jumps" },
  "Band assisted Pullups": { existing: false, name: "Band Assisted Pull-Ups" },
  "Band Assisted Pushup": { existing: false, name: "Band Assisted Pushups" },
  "Band assisted Pushups": { existing: false, name: "Band Assisted Pushups" },
  "Banded Tantrum Kicks": { existing: true, name: "Banded Tantrum Kicks" },
  "Barbeell Back Squat": { existing: true, name: "Barbell Back Squat" },
  "Barbell Back Squat": { existing: true, name: "Barbell Back Squat" },
  "Barbell Backsquat": { existing: true, name: "Barbell Back Squat" },
  "Barbell Bench Press": { existing: true, name: "Barbell Bench Press" },
  "Barbell Hip Thrust": { existing: true, name: "Barbell Hip Thrust" },
  "Barbell RDL": { existing: false, name: "Barbell RDL" },
  "BB Back squat": { existing: true, name: "Barbell Back Squat" },
  "BB Back Squat": { existing: true, name: "Barbell Back Squat" },
  "BB Bent Over Row": { existing: true, name: "Bent Over Row" },
  "BB RDL": { existing: false, name: "Barbell RDL" },
  "Cannon Ball Squat": { existing: false, name: "Cannonball Squat" },
  "Copenhagen dips": { existing: false, name: "Copenhagen Level 2 Dips" },
  "copenhagen level 2": { existing: true, name: "Copenhagen Level 2" },
  "Copenhagen Level 2": { existing: true, name: "Copenhagen Level 2" },
  "copenhagen level 2 dips": { existing: false, name: "Copenhagen Level 2 Dips" },
  "Copenhagen level 2 dips": { existing: false, name: "Copenhagen Level 2 Dips" },
  "Copenhagen Level 2 dips": { existing: false, name: "Copenhagen Level 2 Dips" },
  "copenhagen level 2 hip dips": { existing: false, name: "Copenhagen Level 2 Dips" },
  "DB Chest Fly": { existing: true, name: "Chest Fly" },
  "DB Front Rack Squat": { existing: true, name: "Front Rack Squat" },
  "DB Pullover": { existing: true, name: "Dumbbell Pullover" },
  "DB RDL": { existing: false, name: "DB RDL" },
  "DB Skullcrushers": { existing: true, name: "Skullcrushers" },
  "Depth jump": { existing: false, name: "Depth Jump" },
  "exercise ball tantrum kicks": { existing: false, name: "Exercise Ball Tantrum Kicks" },
  "Exercise Ball Tantrum Kicks": { existing: false, name: "Exercise Ball Tantrum Kicks" },
  "Explosive Keiser Pushpulls": { existing: false, name: "Explosive Keiser Push-Pulls" },
  "Explosive Lateral Step up 6-9\" Box": { existing: false, name: "Explosive Lateral Step Up 6-9\" Box" },
  "explosive lateral step ups": { existing: false, name: "Explosive Lateral Step Ups" },
  "Explosive Lateral Step ups": { existing: false, name: "Explosive Lateral Step Ups" },
  "Explosive Lateral Step ups Non Weighted": { existing: false, name: "Explosive Lateral Step Ups (Non-Weighted)" },
  "Explosive Lateral Step ups Weighted": { existing: false, name: "Explosive Lateral Step Ups (Weighted)" },
  "Feet elevate Glute Bridge with MB squeeze": { existing: false, name: "Feet Elevated Glute Bridge with MB Squeeze" },
  "FFE spilt squat": { existing: false, name: "FFE Split Squat" },
  "FFE split squat": { existing: false, name: "FFE Split Squat" },
  "FFE Split Squat": { existing: false, name: "FFE Split Squat" },
  "FFE split squats": { existing: false, name: "FFE Split Squat" },
  "Foot elevated SL Glute Bridge": { existing: false, name: "Foot Elevated SL Glute Bridge" },
  "Forward Lunge": { existing: true, name: "Forward Lunge" },
  "GHD or Bench Reverse Hyper": { existing: true, name: "GHD or Bench Reverse Hyper" },
  "Goblet cannonball squat": { existing: false, name: "Goblet Cannonball Squat" },
  "Goblet Cannonball Squat": { existing: false, name: "Goblet Cannonball Squat" },
  "Goblet Squat": { existing: true, name: "Goblet Squat" },
  "Half Kneeling to Jump": { existing: false, name: "Half Kneeling to Jump" },
  "Hallow Body Hold": { existing: true, name: "Hollow Body Hold" },
  "Hammer Curls": { existing: true, name: "Hammer Curls" },
  "Hamstring Bridge Catch": { existing: true, name: "Hamstring Bridge Catch" },
  "Hang Clean High Pull": { existing: false, name: "Hang Clean High Pull" },
  "Hang Clean Jump Shrug": { existing: false, name: "Hang Clean Jump Shrug" },
  "Hanging Knee Tucks": { existing: false, name: "Hanging Knee Tucks" },
  "Hanging Weighted Hanging Knee Tucks": { existing: false, name: "Weighted Hanging Knee Tucks" },
  "High Plank DB Pullthrough": { existing: false, name: "High Plank DB Pull-Through" },
  "High to low keiser chops power": { existing: true, name: "High to Low Cable Chop" },
  "k. SL hip extensions with foot turned out": { existing: false, name: "Keiser Hip Extensions Toe Pointing Out" },
  "KB deadlift": { existing: true, name: "Kettlebell Deadlift" },
  "KB swings": { existing: true, name: "Kettlebell Swings" },
  "KB Swings": { existing: true, name: "Kettlebell Swings" },
  "Keiser Abduction": { existing: true, name: "Keiser Abduction" },
  "Keiser Bicep Curls": { existing: false, name: "Keiser Bicep Curls" },
  "Keiser Chops": { existing: true, name: "Keiser Chops" },
  "Keiser Hip Extensions Toe Pointing Out": { existing: false, name: "Keiser Hip Extensions Toe Pointing Out" },
  "Keiser Hip Flexion": { existing: false, name: "Keiser Hip Flexion" },
  "Keiser Straight Leg Hip Flexion": { existing: false, name: "Keiser Straight Leg Hip Flexion" },
  "Landmine Rotations": { existing: false, name: "Landmine Rotations" },
  "Lateral broad jump": { existing: true, name: "Lateral Broad Jump" },
  "Lateral broad Jump": { existing: true, name: "Lateral Broad Jump" },
  "lateral broad jumps": { existing: true, name: "Lateral Broad Jump" },
  "Lateral lunge": { existing: true, name: "Lateral Lunge" },
  "Lateral lunges": { existing: true, name: "Lateral Lunge" },
  "Lateral Raises": { existing: true, name: "Lateral Raises" },
  "Lateral Sled Drag": { existing: false, name: "Lateral Sled Drag" },
  "Lateral Squats": { existing: false, name: "Lateral Squats" },
  "Lateral Step Down 6-9\" box": { existing: true, name: "Lateral Step Down" },
  "Lateral Step Down 6\" Box": { existing: true, name: "Lateral Step Down" },
  "Lateral step down on 6” box": { existing: true, name: "Lateral Step Down" },
  "Lateral Step Downs From 6\" Box": { existing: true, name: "Lateral Step Down" },
  "Lunge jumps": { existing: true, name: "Jumping Lunges" },
  "MB wall ball": { existing: false, name: "MB Wall Ball" },
  "MB Wall Ball": { existing: false, name: "MB Wall Ball" },
  "MB Wall Throw ins": { existing: false, name: "MB Wall Throw-Ins" },
  "Med Ball Slam to Rotational Throw": { existing: false, name: "Med Ball Slam to Rotational Throw" },
  "Med Ball Wall Ball": { existing: false, name: "MB Wall Ball" },
  "Narrow Grip Bench Press": { existing: true, name: "Close Grip Bench Press" },
  "Pallof Press": { existing: true, name: "Pallof Press" },
  "Partner Nordic": { existing: false, name: "Partner Nordic" },
  "Partner nordics": { existing: false, name: "Partner Nordic" },
  "plank dips": { existing: true, name: "Side Plank Dips" },
  "Plyo Pushup": { existing: true, name: "Plyo Pushup" },
  "Reverse Crunch to Leg Lower": { existing: true, name: "Reverse Crunch to Leg Lower" },
  "Reverse Grip Curls": { existing: false, name: "Reverse Grip Curls" },
  "Reverse Lunge": { existing: true, name: "Reverse Lunges" },
  "Reverse Plank Knees To Chest": { existing: true, name: "Reverse Plank Knees To Chest" },
  "RFE Split Squat": { existing: false, name: "RFE Split Squat" },
  "RFE Split squat jumps": { existing: false, name: "RFE Split Squat Jumps" },
  "RFE Split Squat Jumps": { existing: false, name: "RFE Split Squat Jumps" },
  "RFE Split Squats": { existing: false, name: "RFE Split Squat" },
  "Russian Twist": { existing: true, name: "Russian Twist" },
  "Seated DB Arnold Press": { existing: true, name: "Seated DB Arnold Press" },
  "Seated Exercise Ball Tantrum Kicks": { existing: false, name: "Seated Exercise Ball Tantrum Kicks" },
  "Seated Knee Extensions": { existing: false, name: "Seated Knee Extensions" },
  "seated knee tucks": { existing: false, name: "Seated Knee Tucks" },
  "seated leg extensions": { existing: false, name: "Seated Knee Extensions" },
  "Seated leg extensions": { existing: false, name: "Seated Knee Extensions" },
  "Seated Tantrum Kicks": { existing: false, name: "Seated Tantrum Kicks" },
  "Side plank with abduction iso": { existing: false, name: "Side Plank with Abduction Iso" },
  "Single leg elevated glute bridge": { existing: false, name: "Single Leg Elevated Glute Bridge" },
  "single leg hip thrust with MB squeeze": { existing: false, name: "Single Leg Hip Thrust with MB Squeeze" },
  "single leg hip thust with mb squeeze": { existing: false, name: "Single Leg Hip Thrust with MB Squeeze" },
  "Sit to stand jumps": { existing: true, name: "Sit to Stand Jumps" },
  "Sit to Stand Jumps": { existing: true, name: "Sit to Stand Jumps" },
  "skater hops for distance": { existing: false, name: "Skater Hops for Distance" },
  "skater jumps": { existing: false, name: "Skater Jumps" },
  "Skater Squats": { existing: true, name: "Skater Squats" },
  "Skaters for distance": { existing: false, name: "Skater Hops for Distance" },
  "SL Bent Knee Calf Raise ISO": { existing: false, name: "SL Bent Knee Calf Raise ISO" },
  "Sl Broad Jump to Bilateral Landing": { existing: false, name: "SL Broad Jump to Bilateral Landing" },
  "SL Calf Raise ISO": { existing: false, name: "SL Calf Raise ISO" },
  "SL DB Hip Thrust w/ MB Squeeze": { existing: false, name: "Single Leg Hip Thrust with MB Squeeze" },
  "SL Hamstring Bridge ISO": { existing: false, name: "SL Hamstring Bridge ISO" },
  "SL Squat to Bench": { existing: true, name: "single leg squat to bench" },
  "SL Vert Jump to Bilateral Landing": { existing: true, name: "SL Vert Jump to Bilateral Landing" },
  "SL weighted hip thrust w/ MB squeeae": { existing: false, name: "Single Leg Hip Thrust with MB Squeeze" },
  "sled march (heavy)": { existing: true, name: "Sled March" },
  "Sled March (Heavy)": { existing: true, name: "Sled March" },
  "split squat": { existing: true, name: "Split Squats" },
  "Split Squat ISO": { existing: false, name: "Split Squat ISO" },
  "split squats": { existing: true, name: "Split Squats" },
  "Squat jumps": { existing: true, name: "Squat Jumps" },
  "Staggered Stance RDL": { existing: true, name: "Staggered Stance RDL" },
  "standing exercise ball abduction iso": { existing: false, name: "Standing Exercise Ball Abduction Iso" },
  "standing KB knee drive": { existing: false, name: "Standing KB Knee Drive" },
  "straight leg bounds": { existing: false, name: "Straight Leg Bounds" },
  "Suitcase Carry": { existing: true, name: "Suitcase Carry" },
  "sumo squat": { existing: true, name: "Sumo Squats" },
  "Sumo squat": { existing: true, name: "Sumo Squats" },
  "Sumo Squat": { existing: true, name: "Sumo Squats" },
  "Sumo Squats": { existing: true, name: "Sumo Squats" },
  "Tall Kneeling Shoulder Press": { existing: false, name: "Tall Kneeling Shoulder Press" },
  "Trapabar Deadlift": { existing: true, name: "Trapbar Deadlift" },
  "Trapbar Deadlift": { existing: true, name: "Trapbar Deadlift" },
  "Trapbar RDL": { existing: true, name: "Trapbar RDL" },
  "Tricep Dips": { existing: true, name: "Tricep Dips" },
  "TRX Pike Up": { existing: false, name: "TRX Pike Up" },
  "Unevern Farmer's Carry": { existing: false, name: "Uneven Farmer's Carry" },
  "V Sit up": { existing: true, name: "V Sit Ups" },
  "V Situps": { existing: true, name: "V Sit Ups" },
  "Weight Hamstring bridge iso": { existing: false, name: "Weighted Hamstring Bridge Iso" },
  "Weight Squat Jumps": { existing: false, name: "Weighted Squat Jumps" },
  "Weighted Half Kneeling to Jump": { existing: false, name: "Weighted Half Kneeling to Jump" },
  "weighted hamstring bridge iso": { existing: false, name: "Weighted Hamstring Bridge Iso" },
  "Weighted High Plank": { existing: false, name: "Weighted High Plank" },
  "weighted lateral lunge": { existing: false, name: "Weighted Lateral Lunge" },
  "Weighted Pushups": { existing: false, name: "Weighted Pushups" },
  "Weighted Reverse Nordics": { existing: true, name: "Weighted Reverse Nordics" },
  "Weighted Seated to Broad Jump": { existing: false, name: "Weighted Seated to Broad Jump" },
  "Weighted sit to stand jumps": { existing: false, name: "Weighted Sit to Stand Jumps" },
  "Weighted Skater Jumps": { existing: false, name: "Weighted Skater Jumps" },
  "weighted split squat jumps": { existing: false, name: "Weighted Split Squat Jumps" },
  "Weighted squat jumps": { existing: false, name: "Weighted Squat Jumps" },
  "Weighted Wall Sit": { existing: false, name: "Weighted Wall Sit" },

  // Andy Tagmee (added after his U14->U15 move)
  "copenhagen level 2 hold": { existing: true, name: "Copenhagen Plank - Level 2" },
  "lateral step ups": { existing: true, name: "Lateral Step Ups" },
  "alternating v sit ups": { existing: true, name: "Alternating V Sit-Up" },
  "high plank with DB pullthrough": { existing: true, name: "High Plank DB Pull-Through" },
};
